development:
  adapter: postgresql
  database: house_inventory_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: house_inventory_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: house_inventory_production
  pool: 5
  timeout: 5000
